#############################################################################
# Makefile for building: 404Project
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  404Project.pro
# Template: app
# Command: /Applications/QT/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile 404Project.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = 
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/QT/5.3/clang_64/mkspecs/macx-clang -I.
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS)  
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Applications/QT/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c \
		main_old.c \
		linkedlist.c 
OBJECTS       = main.o \
		main_old.o \
		linkedlist.o
DIST          = /Applications/QT/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/QT/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/lex.prf \
		404Project.pro main.c \
		main_old.c \
		linkedlist.c
QMAKE_TARGET  = 404Project
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = 404Project

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 404Project.pro /Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Applications/QT/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/QT/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/lex.prf \
		404Project.pro
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile 404Project.pro
/Applications/QT/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Applications/QT/5.3/clang_64/mkspecs/qdevice.pri:
/Applications/QT/5.3/clang_64/mkspecs/features/device_config.prf:
/Applications/QT/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/unix.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/mac.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/macx.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/clang.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Applications/QT/5.3/clang_64/mkspecs/qconfig.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/qt_config.prf:
/Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/QT/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/QT/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/default_pre.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
/Applications/QT/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/default_post.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/warn_on.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/exceptions.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/yacc.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/lex.prf:
404Project.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile 404Project.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/404Project1.0.0 || mkdir -p .tmp/404Project1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/404Project1.0.0/ && (cd `dirname .tmp/404Project1.0.0` && $(TAR) 404Project1.0.0.tar 404Project1.0.0 && $(COMPRESS) 404Project1.0.0.tar) && $(MOVE) `dirname .tmp/404Project1.0.0`/404Project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/404Project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c removecomments.h \
		removecomments.c \
		linkedlist.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

main_old.o: main_old.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o main_old.o main_old.c

linkedlist.o: linkedlist.c linkedlist.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o linkedlist.o linkedlist.c

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/404Project/bin || mkdir -p $(INSTALL_ROOT)/opt/404Project/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/404Project/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/404Project/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/404Project/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

